# Copyright 2014 VU University Medical Center.
# Licensed under the Apache License version 2.0 (see http://www.apache.org/licenses/LICENSE-2.0.html).

# Travis CI configuration for continuous integration. See https://travis-ci.org/ for more information.
# Author: Freek de Bruijn (f.debruijn@vumc.nl).

language: java
jdk:
  - oraclejdk8
  - oraclejdk7
  - openjdk7
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
after_script:
  - "sh -e /etc/init.d/xvfb stop"
